config/routes.rb
Famtree::Application.routes.draw do
  resources :people
  resources :relationships
  resources :families, :only => [:new, :create, :edit, :update]
  match '/family/join',   to: 'families#join',   via: 'get'
  match '/family/joined',   to: 'families#joined',   via: 'post'

  root :to => 'people#index'

  devise_for :users

end

app/models/family.rb
require 'digest/sha1'

class Family < ActiveRecord::Base
  has_many :people
  has_many :users

  attr_accessor :new_password

  before_save :hash_password

  def hash_password
    password =  Digest::SHA1.hexdigest @new_password
    self.password = password
  end

  def self.authenticate(family_name, password)
    pwd = Digest::SHA1.hexdigest(password)
    fam = Family.where(:family_name => family_name).
                 where(:password => pwd)
    if fam
      fam.first
    else
      nil
    end
  end

end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :family
  has_many :relationships, :foreign_key => 'person'

  validates :first_name, presence: true
  validates :last_name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, allow_blank: true, format: {with: VALID_EMAIL_REGEX}


  scope :by_user, -> (user) {where(:family_id => user.family_id)}

  def name
      "#{first_name} #{last_name}"
  end

  def with_spouse_name
    spouse = PersonManager.new(self).spouse
    if spouse
      "#{first_name} #{last_name} and  #{spouse.first_name} #{spouse.last_name}"
    else
      "#{first_name} #{last_name}"
    end
  end

  def spouse
    spouse = PersonManager.new(self).spouse
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :person, :foreign_key => 'person' 
  belongs_to :relative, :class_name => 'Person', :foreign_key => 'relative'
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :family

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def join_family(family_name, password)
    if family_to_join = Family.authenticate(family_name, password)
      update_attribute(:family, family_to_join)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include ApplicationHelper

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :authenticate_user!

  def new
    @family = Family.new
  end

  def create
    if passwords_match(params)
      @family = Family.new(:family_name=>params[:family][:family_name],
                           :description=> params[:family][:description],
                           :new_password => params[:family][:password])
      if @family.save
        current_user.family = @family
        current_user.save
        redirect_to root_path, :flash => {:success => 'Created new family'}
      end
    else
      redirect_to new_family_path, :flash => {:error => 'Passwords must match'}
    end
  end

  def join
    @family = Family.new
  end

  def joined
    if current_user.join_family(params[:family][:family_name], 
                                params[:family][:password])
      redirect_to root_path, :flash => {:success => 'You joined the family!'}
    else
      redirect_to family_join_path, :flash => {:error => 'That family/password combination is invalid'}
    end

  end

  private
  def family_params
    params.require(:family).permit(:family_name, :description, :password, 
                                   :password_comfirmation)
  end

  def passwords_match(params)
    params[:family][:password] == params[:family][:password_comfirmation]
  end

end

app/controllers/people_controller.rb
require_relative '../../lib/relationship_manager.rb'

class PeopleController < ApplicationController
  before_action :authenticate_user!
  before_action :belongs_to_any_family, only: [:new, :create]
  before_action :belongs_to_correct_family, only: [:show, :edit, :update, :destroy]
  
  def index
    @title = 'Your Family'
    if current_user.family
      @people = FamilyBuilder.new(current_user.family).tree
    else
      flash.notice = 'please make or join a family'
    end
  end

  def show
    @person = Person.find(params[:id])
    @relatives = RelationshipManager.relatives(@person)
  end

  def new
    @person = Person.new
  end

  def create
    params[:person][:family_id] = current_user.family_id
    @person = Person.new(person_params)
    if @person.save
      redirect_to root_path, :flash => {:success => 'Created new person'}
    else
      flash[:alert] = @person.errors.full_messages.join(', ')
      render 'new'
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find_by_id(params[:id])
    if @person.update_attributes(person_params)
      redirect_to root_path, :flash => {:success => 'Successfully updated person'}
    else
      render 'edit'
    end
  end

  def destroy
  end

  private

  def person_params
    params.require(:person).permit(:first_name, :middle_name, :last_name,
                                   :email, :birthday, :family_id)
  end

  def belongs_to_any_family
    unless current_user.family_id
      redirect_to root_path
    end
  end

  def belongs_to_correct_family
    unless current_user.family == Person.find(params[:id]).family
      redirect_to root_path
    end
  end

end

app/controllers/relationships_controller.rb
require_relative '../../lib/relationship_manager.rb'

class RelationshipsController < ApplicationController

  attr_reader :person

  before_filter :authenticate_user!

  def new
    @title = 'Make a new relationship'
    @person = Person.find_by_id(params[:id])
    @relationship = Relationship.new(:person => person)
    @rel_choices = current_user.family.people 
  end

  def create
    relative = Person.find_by_id(params[:relationship][:relative])
    person = Person.find_by_id(params[:relationship][:person])
    relationship = RelationshipManager.new(person).
                   make_relation(relative, 
                                 params[:relationship][:rel_type])
    unless relationship
      redirect_to new_relationship_path({:id =>person.id}),
                  :flash => {:error => 'Invalid Relationship!'}
    else
      redirect_to root_path, :flash => {:success => 'Relationship created!'}
    end
  end

  def destroy
    rel = Relationship.find(params[:id])
    RelationshipManager.new(rel.person).delete_relationship(rel.relative)
    redirect_to root_path, :flash => {:success => 'Relationship deleted!'}
  end

  private
  def rel_params
    params.require(:relationship).permit(:person, :relative, :rel_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def user_signed_in
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

end

app/helpers/relationship_helper.rb
module RelationshipHelper
end

app/views/families/join.html.erb
<h1>Join Family</h1>
<%= form_for @family, :url => {:action => :joined } do |f| %>
  <div class = 'field'>
    <%= f.label :family_name %>
    <%= f.text_field :family_name %>
  </div>
  <div class = 'field'>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class='actions'>
    <%= f.submit "Join Family" %>
  </div>
<% end %>

app/views/families/new.html.erb
<h1> New Family </h1>

<%= form_for(@family) do |f| %>
  <div class='field'>
    <%= f.label :family_name%>
    <%= f.text_field :family_name%>
  </div>
  <div class='field'>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class='field'>
    <%= f.label :password %>
    <%= f.password_field :password%>
  </div>
  <div class='field'>
    <%= f.label :password_comfirmation, "Confirm Password"%>
    <%= f.password_field :password_comfirmation%>
  </div>
  <div class = 'actions'>
    <%= f.submit 'New Family' %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Sign Out", destroy_user_session_path, method: "delete" %></li>
    <li><%= link_to "Join Family", family_join_path %></li>
    <li><%= link_to "New Family", new_family_path %></li>
    <li><%= link_to "New Person", new_person_path %></li>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Famtree</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>

<% flash.each do |key, val| %>
  <div class="alert alert-<%= key %>">
    <%= val %>
  </div>
<% end %>

<%= yield %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/people/_fields.html.erb
  <div class='field'>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class='field'>
    <%= f.label :middle_name %>
    <%= f.text_field :middle_name %>
  </div>
  <div class='field'>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class='field'>
    <%= f.label :email%>
    <%= f.text_field :email%>
  </div>
  <div class='field'>
    <%= f.label :birthday%>
    <%= f.date_field :birthday%>
  </div>

app/views/people/_person.html.erb
<% @people.each do |person| %>
<li>
  <% (0..person[:generation]).each do |i| %>
    <% if i>0 %>
      ----
    <% end %>
  <% end %>
  <%= link_to "#{person[:person].name}", person[:person]%>
  <% if person[:person].spouse %>
    and
    <%= link_to "#{person[:person].spouse.name}", person[:person].spouse%>
  <% end %>
  <%= link_to "edit", edit_person_url(person[:person]) %>
  <%= person[:person].birthday %>
  <%= link_to "new relationship", new_relationship_url(:id => person[:person].id) %>
</li>
<% end %>

app/views/people/create.html.erb
<h1>Person#create</h1>
<p>Find me in app/views/person/create.html.erb</p>

app/views/people/destroy.html.erb
<h1>Person#destroy</h1>
<p>Find me in app/views/person/destroy.html.erb</p>

app/views/people/edit.html.erb
<h1>Person#edit</h1>
<%= form_for(@person) do |f| %>
  <%= render 'fields', :f => f %>

  <div class = 'actions'>
    <%= f.submit 'Update' %>
  </div>
<% end %>

app/views/people/index.html.erb
<h1>Person#index</h1>

<ul class = 'people'>
  <% if @people %>
    <%= render :partial=> '/people/person' %>
  <% end %>
</ul>

app/views/people/new.html.erb
<h1>Person#new</h1>
<%= form_for(@person) do |f| %>
  <%= render 'fields', :f => f %>

  <div class='actions'>
    <%= f.submit "Save New Person" %>
  </div>
<% end %>

app/views/people/show.html.erb
<h1>Person#show</h1>

<div class = 'person'>
  <%= @person.name %></br>
  email: <%= @person.email%></br>
  Birthday: <%= @person.birthday %></br>
</div>

<% @relatives.each do |r| %>
  <%= r.rel_type %> of 
  <%= r.relative.name %>
  <%= r.id %>
  <%= link_to "delete", r, :controller => :relationships_controller,
                           :method => :delete,
                           :data => {:confirm => 'delete this relationship?'}
  %>
                                           
  </br>
<% end %>

app/views/people/update.html.erb
<h1>Person#update</h1>
<p>Find me in app/views/person/update.html.erb</p>

app/views/relationships/create.html.erb
<h1>Relationship#create</h1>
<p>Find me in app/views/relationship/create.html.erb</p>

app/views/relationships/delete.html.erb
<h1>Relationship#delete</h1>
<p>Find me in app/views/relationship/delete.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationship#destroy</h1>
<p>Find me in app/views/relationship/destroy.html.erb</p>

app/views/relationships/edit.html.erb
<h1>Relationship#edit</h1>
<p>Find me in app/views/relationship/edit.html.erb</p>

app/views/relationships/new.html.erb
<h1>Relationship#new</h1>
new relationship for
<%= @person.name %>
<%= form_for(@relationship, url: {action: 'create'}) do |f| %>
  <div class = 'field'>
  <%= f.hidden_field :person %>
</div>
  <div class = 'field'>
    <%= @person.name %> is the
    <%= f.select(:rel_type, ['', 'Child', 'Parent', 'Spouse']) %> of
    <%= f.select(:relative, @rel_choices.map{ |r| [r.name, r.id]}, :include_blank => true) %>
</div>
<div class = 'actions'>
  <%= f.submit 'Save Relationship' %>
</div>
<% end %>

app/views/relationships/update.html.erb
<h1>Relationship#update</h1>
<p>Find me in app/views/relationship/update.html.erb</p>